[package]
name = "ferry-core"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
names = "0.14.0"
mdns-sd = "0.16.0"
anyhow = "1.0.100"
hostname = "0.4.1"
libmdns = "0.9"
log = "0.4.28"